name=input('Enter your name: ')
branch=input('Enter your Branch: ')
gender=input('Enter your gender: ')
college=input('Enter your college name: ')
age=int(input('enter your age: '))
print('Your name is',name)
print('Your brach is',branch)
print('Your gender is',gender)
print('Your college name is',college)
print('Your age is',age)
